### PR TITLE
Make manager a singleton

### LINKED ISSUE #11: Manager - initialization & destruction
Consider following code:
```{.cpp}
    while( true ) {
		rb::Manager man;
        man.leds().yellow(true);
        rb::delay( 200ms );
        man.leds().yellow(false);
        rb::delay( 200ms );
    }
```

causes the ESP to crash as abort is called when the I2C driver is initialized for the second time.

Such behavior is OK, however, the error message is not clear (actually you have to go through backtrace to find the reason for `abort` call.). Such behavior is hard for the beginners, and it can confuse them.

I would consider one of the following:
- making the manager a proxy (i.e. I can construct as many managers as I want, but they will all point to a single instance)
- making the manager a singleton
- adding a check if there is already an instance of a manager and throwing an appropriate error message

### PR DESCRIPTION
**Pull request by Tasssadar**
Closes #11

### CODE REVIEW

File: src/RBControl_manager.hpp [hunk 1]
```diff
@@ -20,31 +20,48 @@ namespace rb {
...
+        static Manager instance;
+        return instance;
+    }
+
+    /**
+     * \brief Initialize the manager - must be called once at the start of the program.
      *
-     * \param enable_motor_failsafe `true` activate the automatic failsafe, `false` deactivate this system
-     * \param enable_battery `true` activates the battery voltage measurement and management.
+     * \param flags modify the manager's behavior or toggle some features. See ManagerInstallFlags enum.
```
Comment (JarekParal) [inline src/RBControl_manager.hpp]: It will be better to use @{ManagerInstallFlags}

File: src/RBControl_manager.hpp [hunk 2]
```diff
@@ -20,31 +20,48 @@ namespace rb {
...
+     * \brief Get manager instance.
      *
-     * The `enable_motor_failsafe` parameter toggles the automatic failsafe, where the manager
-     * will automatically turn all motors off if it does not receive any motor set calls
-     * in 300ms. This is to stop the robot when the controller is disconnected.
-     *
-     * The `enable_battery` parameter enables battery voltage measurement and auto-shutdown
-     * when the voltage is low.
+     * Always return the same instance and is thread-safe. Do not forget to call install() to initialize
+     * the manager at the start of your program.
```
Comment (JarekParal) [inline src/RBControl_manager.hpp]: Modify description?
```
...  at the start of your program after you get the instance.
```

Also if doxygene support links to example, it will be good to add the link.

File: examples/motors/main.cpp [hunk 3]
```diff
@@ -17,12 +18,12 @@ void setup() {
                 20, 20);
         delay(1000);
 
-        man.setMotors().power(rb::MotorId::M1, 0).power(rb::MotorId::M2, 0).set();
+        rb::Manager::get().setMotors().power(rb::MotorId::M1, 0).power(rb::MotorId::M2, 0).set();
```
Comment (JarekParal) [inline examples/motors/main.cpp:21]: Do you prefer using `rb::Manager::get()` instead
```cpp
auto& man = rb::Manager::get();

man.someFunction(); // in the whole program 
```

Or these two variants are here just to show the possibilities?

File: src/RBControl_battery.cpp [hunk 4]
```diff
@@ -14,24 +14,24 @@
...
-        adc1_config_channel_atten(BATT_ADC_CHANNEL, ADC_ATTEN_DB_11);
+Battery::~Battery() {
 
-        updateVoltage();
-    }
 }
 
-Battery::~Battery() {
+void Battery::install() {
+    m_expander.digitalWrite(POWER_OFF_EXPANDER, 1);
```
Comment (JarekParal) [inline src/RBControl_battery.cpp]: The line disable the IO expander?

Comment (JarekParal) [reply src/RBControl_battery.cpp]: Or what does it do?

It isn't clear for me from the source code.

**Review by JarekParal — COMMENTED** [review]
Looks good.

Just add a few questions and tips for improves.

**Comment by JarekParal** [comment]
PS: Is that already released? @Tasssadar 

I didn't find any notes about that in [Release notes](https://github.com/RoboticsBrno/RB3201-RBControl-library/releases).

File: src/RBControl_battery.cpp (hunk 4 above)
Comment (Tasssadar) [reply src/RBControl_battery.cpp]: I think this is the pin that keeps the board turned on, see the shutdown method: https://github.com/RoboticsBrno/RB3201-RBControl-library/blob/master/src/RBControl_battery.cpp#L48

I think if I don't do anything with it, the board stays on anyway, but I think it is a good idea to initialize it here so the shutdown() method works even when the battery management is disabled.

File: src/RBControl_manager.hpp (hunk 1 above)
Comment (Tasssadar) [reply src/RBControl_manager.hpp]: Didn't know about this, thanks!

File: src/RBControl_manager.hpp (hunk 2 above)
Comment (Tasssadar) [reply src/RBControl_manager.hpp]: Fixed.

File: src/RBControl_battery.cpp (hunk 4 above)
Comment (Tasssadar) [reply src/RBControl_battery.cpp]: Moved this pin's initialization to manager.cpp to setupExpander, as it should be kept in 1 to keep the board on.

**Comment by Tasssadar** [comment]
> PS: Is that already released? @Tasssadar
> 
> I didn't find any notes about that in [Release notes](https://github.com/RoboticsBrno/RB3201-RBControl-library/releases).

? Not sure what you mean, this is just a pull request still.

File: examples/motors/main.cpp (hunk 3 above)
Comment (Tasssadar) [reply examples/motors/main.cpp:21]: Yep, to show that it is possible to just use ::get() again.

**Comment by yaqwsx** [comment]
I think also move constructor and assign operator should be marked as deleted. Otherwise, the following can break the system:
```{.cpp}
rb::Manager man = std::move(rb::Manager::get())
```

File: src/RBControl_battery.cpp (hunk 4 above)
Comment (JarekParal) [reply src/RBControl_battery.cpp]: Ok, then I would like to suggest changing the name of define from the `POWER_OFF_EXPANDER` to `BOARD_POWER_OFF_PIN_ON_EXPANDER`.

**Comment by JarekParal** [comment]
> > PS: Is that already released? @Tasssadar
> > I didn't find any notes about that in [Release notes](https://github.com/RoboticsBrno/RB3201-RBControl-library/releases).
> 
> ? Not sure what you mean, this is just a pull request still.

I wanted to ask you if this code/PR is already released?

**Comment by Tasssadar** [comment]
> I wanted to ask you if this code/PR is already released?

No, only whatever is in the master branch is "released", plus platform.io hub takes only the tagged commits (which are done in master branch every now and then).

**Comment by Tasssadar** [comment]
> I think also move constructor and assign operator should be marked as deleted. Otherwise, the following can break the system:
> 
> ```
> rb::Manager man = std::move(rb::Manager::get())
> ```

@yaqwsx When you supply a copy constructor (even deleted), the move constructor is not autogenerated, so the line you posted does not work.

**Comment by yaqwsx** [comment]
@Tasssadar: Ok, perfect.
